name: Build packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    container: 
      image: ghcr.io/kreatolinux/builder:latest
      volumes:
        - /var/cache/kpkg/archives:/var/cache/kpkg/archives 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Cache built packages
        uses: actions/cache@v3
        with:
          path: /var/cache/kpkg/archives
          key: cache-nyaa-tarballs

      - name: Build packages
        run: |
          make deps
          make kreastrap
          ./out/kreastrap buildPackages

