name: Format Nim Files

on:
  push:
    paths:
      - '**.nim'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
      - name: Run nimpretty
        run: cd "$GITHUB_WORKSPACE" && nimpretty $(find . -type f -name '*.nim')
      - name: Commit nimpretty Fixes
        uses: EndBug/add-and-commit@v5
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
